# Generated by Django 2.2.8 on 2019-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delv',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
