# Generated by Django 2.2.8 on 2019-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
