# Generated by Django 2.2.8 on 2019-12-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_ordereditem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='ordered',
        ),
    ]
