# Generated by Django 2.2.8 on 2019-12-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_ordereditem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='orderd',
            field=models.BooleanField(default=False),
        ),
    ]
