# Generated by Django 2.2.8 on 2019-12-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_ordereditem_orderd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
