# Generated by Django 2.2.8 on 2019-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
