# Generated by Django 2.2.8 on 2019-12-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_remove_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
