# Generated by Django 2.2.8 on 2019-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_remove_cart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
